# Cache downloaded dependencies and plugins between builds.
# Not strictly necessary, but speeds up the builds.
cache:
    key: "$CI_JOB_NAME"
    paths:
        # Must be within the repository under test hence we can't use the
        # default ~/.m2
        - .m2/repository
variables:
  # This will suppress any download for dependencies and plugins or upload messages which would clutter the console log.
  # `showDateTime` will show the passed time in milliseconds. You need to specify `--batch-mode` to make this work.
  MAVEN_OPTS: "-Dhttps.protocols=TLSv1.2 -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true"
  # As of Maven 3.3.0 instead of this you may define these options in `.mvn/maven.config` so the same config is used
  # when running from the command line.
  # `installAtEnd` and `deployAtEnd` are only effective with recent version of the corresponding plugins.
  MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end --show-version -DinstallAtEnd=true -DdeployAtEnd=true"


deploy:
    image: maven:3.6.1-jdk-11 # docker image with Maven
    before_script:
        # The runners on the forge need a proxy to access the web. mvn
        # ignores the $http_proxy & friends variable => write a
        # configuration file that does this for us.
        - . ci/setup-mvn-proxy.sh
        # Useful only for debugging
        # - cat ~/.m2/settings.xml
        - chmod 400 $CI_SSH_KEY
    script:
        - mvn clean package --batch-mode
        - scp -o StrictHostKeyChecking=no -i $CI_SSH_KEY /builds/p1710759/m1if13-tps/target/mif13-0.0.1-SNAPSHOT.jar gitlabci@192.168.75.13:/opt/tomcat/webapps/mif13-0.0.1-SNAPSHOT.jar
        
